---
- name: k3s installation
  hosts: pilot-11
  become: true
  gather_facts: false

  tasks:

  - name: Insert a line at the end of a file.
    lineinfile:
      path: /boot/cmdline.txt
      line: cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
    register: task_result

  - name: Reboot immediately if there was a change.
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
    when: task_result is changed

  - name: Wait for the reboot to complete if there was a change.
    wait_for_connection:
      connect_timeout: 300
      sleep: 5
      delay: 5
      timeout: 300
    when: task_result is changed

  - name: Install necessary packages
    apt:
      name:
        - ntpdate
        - python3-pip
        # - apt-transport-https
        - ca-certificates 
        # - curl 
        # - software-properties-common
      state: present

  - name: Update CA certificates
    command: sudo update-ca-certificates -f

  # - name: Install a list of packages
  #   copy:
  #     src: k3s-1.20.11-k3s1.tar.gz
  #     dest: /home/pilot

  # - name: Extract foo.tgz into /var/lib/foo
  #   ansible.builtin.unarchive:
  #     src: k3s-1.20.11-k3s1.tar.gz
  #     dest: /home/pilot

  # - name: Extract foo.tgz into /var/lib/foo
  #   command: ./install.sh
  #   args:
  #     chdir: /home/pilot/k3s-1.20.11-k3s1

  - name: Disable swap
    command: sudo swapoff -a 

  - name: Launch k3s master
    shell: curl -sfL https://get.k3s.io | K3S_TOKEN="pilot" sh -s - server # --cluster-init
    become: false 

  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path:  /etc/rancher/k3s/k3s.yaml
      owner: pilot
      group: pilot
      mode: u+x,g-x




