---
- name: Configure network based on hostname
  hosts: unknown_pilot
  gather_facts: true
  become: true
  vars: 
    config_path: /etc/dhcpcd.conf
    target_pilot: 5

  tasks:

  # - name: Delete file
  #   file: 
  #     path: dhcpcd.conf
  #     state: absent

### TODO: Consider reversed operation: from ip address set apropriate  hostname

  # - name: Get number of hostname
  #   shell: "echo  {{ansible_hostname | regex_replace('[^0-9]','')}}"

  - name: Edit static ip_address
    lineinfile:
      path: '{{ config_path }}'
      regexp: '^static ip_address=\d*.\d*.\d*.\d*'
      line: 'static ip_address=100.100.100.{{ target_pilot }}/24' 
      state: present

### TODO: change in /etc/hosts
  
  # - name: Edit static routers
  #   lineinfile:
  #     path: '{{ config_path }}'
  #     regexp: '^static routers=\d*.\d*.\d*.\d*'
  #     line: 'static routers=192.168.88.1'
  #     state: present
   
  # - name: Edit static domain_name_servers
  #   lineinfile:
  #     path: '{{ config_path }}'
  #     regexp: '^static domain_name_servers=.*$'
  #     line: "static domain_name_servers=192.168.88.1 8.8.8.8" 
  #     state: present          

  # - name: Make sure dhcp is disabled
  #   lineinfile:
  #     path: '{{ config_path }}'
  #     regexp: '^nodhcp$'
  #     insertafter: '^interface eth0$'
  #     line: 'nodhcp'
  #     state: present

  # - name: Check ip correctness
  #   shell: "echo {{ansible_default_ipv4.address}}"

  - name: Restart dhcpcd service, also issue daemon-reload to pick up config changes
    systemd:
      state: restarted
      daemon_reload: yes
      name: dhcpcd

  - name: Set a hostname
    hostname:
      name: pilot-{{target_pilot}}
  
  # - name: Flush ip addresses on eth0 interface
  #   shell: ip addr flush dev eth0 
