---
- name: Docker installation
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

  #TODO: ansible-galaxy collection install community.general --ignore-certs

  - name: Install ansible python packages
    pip:
      name:
        - docker
        - requests
      executable: pip3
      extra_args: --user

  - name: Stop prometheus container on server
    docker_container:
      name: prometheus
      state: absent      

  - name: Create a prometheus volume
    docker_volume:
      name: prometheus-data

  - name: Template a prometheus config file
    ansible.builtin.template:
      src: /home/com331-b/project-rpi-cluster/monitoring/server/prometheus/prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml

    
  - name: Start prometheus monitoring container on server
    docker_container:
      name: prometheus
      image: prom/prometheus
      state: started
      restart: yes
      restart_policy: always
      ports:
        - 9090:9090
      user: root
      command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=2d'
      volumes:
        - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus-data:/prometheus


  - name: Stop grafana container on server
    docker_container:
      name: grafana
      state: absent

  - name: Create a grafana volume
    docker_volume:
      name: grafana-data
      recreate: always

  - name: Start grafana container on server
    docker_container:
      name: grafana
      image: grafana/grafana
      state: started
      restart: yes
      restart_policy: always
      ports:
        - "3000:3000"
      volumes:
        - grafana-data:/var/lib/grafana

  - name: Create a volume
    docker_volume:
      name: node-exporter-storage
      recreate: always

  - name: Start node-exporter container 
    docker_container:
      name: node-exporter
      image: quay.io/prometheus/node-exporter:latest
      state: started
      restart: yes
      restart_policy: always
      network_mode: host
      pid_mode: host
      read_only: yes
      volumes:
        - /:/host:ro,rslave