---
- name: Docker installation
  hosts: cluster
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  #become: true
  tasks:

  - name: Download docker.sh installer
    get_url:
      url: https://get.docker.com
      dest: /tmp/docker.sh
      validate_certs: no

  - name: Run a docker installation script 
    ansible.builtin.script: /tmp/docker.sh

  - name: Add the user 'pilot' appending the group 'docker'
    ansible.builtin.user:
      name: pilot
      groups: docker
      append: yes

  - name: Start container with block device read limit
    docker_container:
      name: prometheus
      image: prom/prometheus
      state: started
      volumes:
        - /home/com331-b/project-rpi-cluster/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml


  # - name: Start container with block device read limit
  #   docker_container:
  #     name: node-exporter
  #     image: quay.io/prometheus/node-exporter:latest
  #     state: started
  #     network_mode: host
  #     pid_mode: host
  #     volumes:
  #       - /:/host:ro,rslave

