---
- name: Configure network based on hostname
  hosts: cluster
  gather_facts: true
  become: true
  vars: 
    config_path: /etc/dhcpcd.conf

  tasks:

  # - name: Delete file
  #   file: 
  #     path: dhcpcd.conf
  #     state: absent

### TODO: Consider reversed operation: from ip address set apropriate  hostname

  # - name: Get number of hostname
  #   shell: "echo  {{ansible_hostname | regex_replace('[^0-9]','')}}"

  - name: Edit static ip_address
    lineinfile:
      path: '{{ config_path }}'
      regexp: '^static ip_address=\d*.\d*.\d*.\d*'
      line: 'static ip_address=100.100.100.{{ ansible_hostname | regex_replace("[^0-9]","")}}/24' 
      state: present

### TODO: change in /etc/hosts

  - name: Edit static routers
    lineinfile:
      path: '{{ config_path }}'
      regexp: '^static routers=\d*.\d*.\d*.\d*'
      line: 'static routers=100.100.100.100'
      state: present 

  - name: Edit static domain_name_servers
    lineinfile:
      path: '{{ config_path }}'
      regexp: '^static domain_name_servers=.*$'
      line: "static domain_name_servers=100.100.100.100 8.8.8.8" 
      state: present    

  - name: Make sure dhcp is disabled
    lineinfile:
      path: '{{ config_path }}'
      regexp: '^nodhcp$'
      insertafter: '^interface eth0$'
      line: 'nodhcp'
      state: present

  - name: Check ip correctness
    shell: "echo {{ansible_default_ipv4.address}}"

  - name: Restart dhcpcd service, also issue daemon-reload to pick up config changes
    systemd:
      state: restarted
      daemon_reload: yes
      name: dhcpcd
  
  # - name: Flush ip addresses on eth0 interface
  #   shell: ip addr flush dev eth0 
